### ISSUE TITLE
Don t problem a question

### ISSUE THREAD

**Issue by DesertFernanfer** [TheWNetwork/twn-api-upload#1]
Hello, good job for your code but i m sorry to ask you this but you know to connect api? i m noob here in python and i try to connect the apiwith my code 
import requests
url = "https://www.linkbox.to/api/open/file_rename"
params = {
    "itemId":"ZnA0OTkwMDA0dTI30",
    "name":"helloworld.mp4",
    "token":"token"
}

# Realizar la solicitud GET
response = requests.get(url, params=params)

# Verificar la respuesta
if response.status_code == 200:
    print("Archivo renombrado con éxito")
    print(response.json())  # Mostrar la respuesta JSON
else:
    print("Error al renombrar el archivo")
    print(response.text)
   but always sen me error 
   {'msg': 'not permit ', 'status': 403}
  I have searched the internet for information to solve it but I can't find anything, if it bothers you that I ask you, tell me so I can delete this message. Thank you

**Comment by yuuues** [comment]
Buenas,

Sin analizar un poco mas y hacer pruebas, lo único que se me ocurre es que el "itemId" no sea correcto. Si estás copiando el contenido de alguien, creo que tienes que descargarlo primero con "file_save" y luego cambiarle el nombre.

Linkbox no da muy buena información en su API, así que no te puedo ayudar mucho...

**Comment by DesertFernanfer** [comment]
Hola, muchisimas gracias por tu respuesta creo que voy a usar otra nube como mediafire, pero gracias 👍

**Comment by DesertFernanfer** [comment]
Hola he podido solucionarlo si el problema era el itemId que lo cojia de la url, muchisismas gracias por tu ayuda feliz san valentin
