### ISSUE TITLE
Telebox Upload Problem - {'msg': 'file upload error, plz try later', 'status': 500}

### ISSUE THREAD

**Issue by JemPH** [TheWNetwork/twn-api-upload#2]
**When Uploading Image:**

Root folder ID for "hudhiaoida1235" is 40112953
Start uploading...
2024-03-25 21:34:04 - Uploading file: Dolby-Atmos-Logo.png
Uploading: 100%|███████████████████████████████████████████████████████████████████████████████████| 25.4k/25.4k [00:00<00:00, 80.9kB/s]
{'data': {'itemId': 'fp4hdg000lfq'}, 'status': 1}
Folder Name "hudhiaoida1235" link: https://www.linkbox.to/a/d/v9tVTiV
End uploading...

**When Uploading Other Files:**

Root folder ID for "hudhiaoida1235" is 40112953
Start uploading...
2024-03-25 21:32:49 - Uploading file: jaigen.wav
Uploading: 100%|███████████████████████████████████████████████████████████████████████████████████| 4.24M/4.24M [00:02<00:00, 2.09MB/s]
{'msg': 'file upload error, plz try later', 'status': 500}
Folder Name "hudhiaoida1235" link: https://www.linkbox.to/a/d/9RVdpdM
End uploading...

This is my custom version of your repository to display link and print response from the api. I encounter this problem notice that the script only uploads image but when you try to upload other files it does have an error and no files stored. Hope if have fix on this issue.

**Comment by yuuues** [comment]
I though i answered this last month, sorry.

Theorically, telebox only allows images and videos. If you desire to make a pull request to add the iink, would be nice :D 

Also, i've fixed several things on the code and now its possible to upload recursively
