### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by djsaikrishna** [TheWNetwork/twn-api-upload#3]
can u cretate telebox index  like google drive index

**Comment by yuuues** [comment]
Could you explain a bit more? 

'Cause the intention of this code is only to upload data directly to telebox instead of using their crappy upload modal

**Comment by djsaikrishna** [comment]
https://gitlab.com/GoogleDriveIndex/Google-Drive-Index
please check this

i want to access my telebox files videos in web

**Comment by yuuues** [comment]
Sorry, but Telebox does not give that information in their public API so i cannot give that
