### ISSUE TITLE
How to properly fill out `base.env`?

### ISSUE THREAD

**Issue by oknchm** [TheWNetwork/twn-api-upload#4]
So, I've filled out the values of the `base.env` like so:

```
# user variables
USR_LIMIT_CONCURRENT=10

TELEBOX_TOKEN=[redacted]
TELEBOX_API=
TELEBOX_BASEFOLDER=4431XXXX

TERABOX_API=
TERABOX_ROUTE=
``` 

Is `TELEBOX_API` supposed to be blank? If not, where to find the values for it? Can't find any info about it on the `README` file.

Thank you!

**Comment by yuuues** [comment]
Hi

The base.env file is like 

```
# user variables
USR_LIMIT_CONCURRENT=10

TELEBOX_API=[Data from https://www.linkbox.to/admin/account, TOKEN]
TELEBOX_BASEFOLDER=

TERABOX_API=
TERABOX_ROUTE=
```


i fix the readme 'cause the text in it not correct (its from an older version, my bad)

**Comment by oknchm** [comment]
Thanks for the fix! 

I've changed my `base.env` like this:
```
# user variables
USR_LIMIT_CONCURRENT=10

TELEBOX_API=2zXXXXXXXXXXXXXX
TELEBOX_BASEFOLDER=4431XXXX

TERABOX_API=
TERABOX_ROUTE=
```

But I still can't upload files. I'm getting `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

Here's the full log:
```
C:\Users\OKNCHM\Desktop\twn-api-upload-master>python -m app --telebox --dir D:\Folder1 --foldername Folder1
Current date is: 2024-06-13 04:46:18
Telebox
Traceback (most recent call last):
  File "C:\Users\OKNCHM\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\OKNCHM\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\OKNCHM\Desktop\twn-api-upload-master\app\__main__.py", line 25, in <module>
    TeleboxImpl(args)
  File "C:\Users\OKNCHM\Desktop\twn-api-upload-master\app\teleboximp.py", line 18, in __init__
    self.main(arguments)
  File "C:\Users\OKNCHM\Desktop\twn-api-upload-master\app\teleboximp.py", line 55, in main
    folder_pid = int(arguments.basefolder or Config.TELEBOX_BASEFOLDER)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by yuuues** [comment]
If "folder1" is the folder you wanna upload, the parameters should be 

```cmd
python -m app --telebox --dir D:\ --foldername Folder1
```

Folder1 will be the folder you will create on the TELEBOX_BASEFOLDER

You can put inside "Folder1" all folders you want also, recursively

**Comment by oknchm** [comment]
Tried `python -m app --telebox --dir D:\ --foldername Folder1` but still getting `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`. Not sure what I'm doing wrong. ☹️

![Screenshot 2024-06-16 011707](https://github.com/TheWNetwork/twn-api-upload/assets/86455151/25e8fd81-2203-47b2-aa48-1520f79d414c)
![Screenshot 2024-06-16 012213](https://github.com/TheWNetwork/twn-api-upload/assets/86455151/108b0719-bc04-45d8-82e1-10c7a1d88a5d)

My `base.env`:
```
# user variables
USR_LIMIT_CONCURRENT=10

TELEBOX_API=2zXXXXXXXXXXXXXX
TELEBOX_BASEFOLDER=4488XXXX

TERABOX_API=
TERABOX_ROUTE=
```

**Comment by yuuues** [comment]
I'll put you an example:

I have the following

`python -m app --telebox --dir="D:\TX-downloads" --foldername="upload"`

Then, the files i wanna upload are at:

"D:\TX-downloads\upload\ {folders and files to upload}"


Anyway, reading your error more with more detail now ^^

```
    folder_pid = int(arguments.basefolder or Config.TELEBOX_BASEFOLDER)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

The app does not upload the files at the top folder, it needs a folder inside it

I'll note that to upgrade that to allow files at the top folder
