### ISSUE TITLE
Ask… ..

### ISSUE THREAD

**Issue by Hetlr88** [TheWNetwork/twn-api-upload#5]
This api valid to create bot to upload from linkbox to telegram? :) ?

**Comment by yuuues** [comment]
You can use the code for anything you want

**Comment by Hetlr88** [comment]
The method still working?

**Comment by Hetlr88** [comment]
Is it possible to merge this project with twn-ubot-uploadFiles?

**Comment by yuuues** [comment]
> Is it possible to merge this project with twn-ubot-uploadFiles?

Its currently not planned. But i note that as a good upgrade for the future
